#!/bin/bash
set -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
project_dir=$script_dir/..

cd $project_dir
# rm -rf ./bin 2> /dev/null
find ./src -type f -name "*.java" | xargs javac -d ./bin
find ./tests -type f -name "*.java" | xargs javac

echo "Package is successfully built."

