#!/bin/bash
set -e

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
project_dir=$script_dir/..

cd $project_dir/tests/helloworld/

rm -rf sootOutput 2> /dev/null
javac HelloWorld.java

# Produce the first iteration of soot output
java IdentityInstrument HelloWorld main

# Discard the original .class file (always different from soot
cp sootOutput/HelloWorld.class .

# Produce the second iteration based on the first iteration
rm -rf sootOutput
java IdentityInstrument HelloWorld main

set +e
# Compare two iterations. Should be identical and return 0
cmp HelloWorld.class sootOutput/HelloWorld.class

ret=$?
if [ $ret -ne 0 ]; then
  echo "Hello World (identity instrument) test failed: produced different results the 2nd time"
else
  echo "Test (identity instrument) passed"
fi
